[package]
name = "recursive_dir_walk"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.release]
debug = true
lto = "fat"

[dependencies]
flume = "0.10.13"
libc = "0.2.126"
syscalls = "0.6.1"
